<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in the Configuration section of the admin interface.

// Generated from 'domserver-static.php.in' on Sun Feb 25 05:58:46 PM EST 2024.

define('DOMJUDGE_VERSION', '8.2.2');

define('BINDIR',      '/home/a25ra0631/domjudge/domserver/bin');
define('ETCDIR',      '/home/a25ra0631/domjudge/domserver/etc');
define('WEBAPPDIR',   '/home/a25ra0631/domjudge/domserver/webapp');
define('LIBDIR',      '/home/a25ra0631/domjudge/domserver/lib');
define('SQLDIR',      '/home/a25ra0631/domjudge/domserver/sql');
define('LIBVENDORDIR','/home/a25ra0631/domjudge/domserver/lib/vendor');
define('LOGDIR',      '/home/a25ra0631/domjudge/domserver/log');
define('RUNDIR',      '/home/a25ra0631/domjudge/domserver/run');
define('TMPDIR',      '/home/a25ra0631/domjudge/domserver/tmp');

define('BASEURL',     'https://example.com/domjudge/');
